spring:
  application:
    name: torneo_germans_bisbal_api

  datasource:
    url: jdbc:mysql://localhost:3306/torneo_germans_bisbal_db
    username: root
    password: rootroot

  jpa:
    hibernate:
      ddl-auto: create-drop

    show-sql: true

  web:
    error:
      include-stacktrace: never

